/* ------------ Dracula Palette ------------ */
#define DRACULA_BLACK "{282a36}"
#define DRACULA_WHITE "{f8f8f2}"
#define DRACULA_BLACKPURPLE "{6272a4}"
#define DRACULA_CYAN "{8be9fd}"
#define DRACULA_GREEN "{50fa7b}"
#define DRACULA_ORANGE "{ffb86c}"
#define DRACULA_PINK "{ff79c6}"
#define DRACULA_PURPLE "{bd93f9}"
#define DRACULA_RED "{ff5555}"
#define DRACULA_YELLOW "{f1fa8c}"

#define HEX_DRACULA_BLACK (0x282a36ff)
#define HEX_DRACULA_WHITE (0xf8f8f2ff)
#define HEX_DRACULA_BLACKPURPLE (0x6272a4ff)
#define HEX_DRACULA_CYAN (0x8be9fdff)
#define HEX_DRACULA_GREEN (0x50fa7bff)
#define HEX_DRACULA_ORANGE (0xffb86cff)
#define HEX_DRACULA_PINK (0xff79c6ff)
#define HEX_DRACULA_PURPLE (0xbd93f9ff)
#define HEX_DRACULA_RED (0xff5555ff)
#define HEX_DRACULA_YELLOW (0xf1fa8cff)