/* ---------- Tomorrow Palette ---------- */
// Tomorrow Night
/*
#define TOMORROW_BLACK "{1d1f21}"
#define TOMORROW_WHITE "{c5c8c6}"
#define TOMORROW_GRAY "{969896}"
#define TOMORROW_RED "{cc6666}"
#define TOMORROW_ORANGE "{de935f}"
#define TOMORROW_YELLOW "{f0c674}"
#define TOMORROW_GREEN "{b5bd68}"
#define TOMORROW_AQUA "{8abeb7}"
#define TOMORROW_BLUE "{81a2be}"
#define TOMORROW_PURPLE "{b294bb}"

#define HEX_TOMORROW_BLACK (0x1d1f21ff)
#define HEX_TOMORROW_WHITE (0xc5c8c6ff)
#define HEX_TOMORROW_GRAY (0x969896ff)
#define HEX_TOMORROW_RED (0xcc6666ff)
#define HEX_TOMORROW_ORANGE (0xde935fff)
#define HEX_TOMORROW_YELLOW (0xf0c674ff)
#define HEX_TOMORROW_GREEN (0xb5bd68ff)
#define HEX_TOMORROW_AQUA (0x8abeb7ff)
#define HEX_TOMORROW_BLUE (0x81a2beff)
#define HEX_TOMORROW_PURPLE (0xb294bbff)
*/

// Tomorrow Night
#define TOMORROW_BLACK "{4d4d4c}"
#define TOMORROW_WHITE "{efefef}"
#define TOMORROW_GRAY "{8e908c}"
#define TOMORROW_RED "{c82829}"
#define TOMORROW_ORANGE "{f5871f}"
#define TOMORROW_YELLOW "{eab700}"
#define TOMORROW_GREEN "{718c00}"
#define TOMORROW_AQUA "{3e999f}"
#define TOMORROW_BLUE "{4271ae}"
#define TOMORROW_PURPLE "{8959a8}"

#define HEX_TOMORROW_BLACK 0x4d4d4cff
#define HEX_TOMORROW_WHITE 0xefefefff
#define HEX_TOMORROW_GRAY 0x8e908cff
#define HEX_TOMORROW_RED 0xc82829ff
#define HEX_TOMORROW_ORANGE 0xf5871fff
#define HEX_TOMORROW_YELLOW 0xeab700ff
#define HEX_TOMORROW_GREEN 0x718c00ff
#define HEX_TOMORROW_AQUA 0x3e999fff
#define HEX_TOMORROW_BLUE 0x4271aeff
#define HEX_TOMORROW_PURPLE 0x8959a8ff